version: '3.4'

services:
  serverraccoltalatte:
    build:
      context: .
      dockerfile: Dockerfile
    # image: "ghcr.io/matteo0301/server_raccolta_latte:main"
    environment:
      NODE_ENV: production
    volumes:
      # - /var/log/matteo/errors:/usr/src/app/errors
      # - /var/log/matteo/logs:/usr/src/app/logs
      - /home/matteo2001/flutter/web:/usr/src/app/public-flutter
      - /home/matteo2001/.env:/usr/src/app/.env
    ports:
      - 443:443
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

    hostname: mongodb

    # Uncomment to change startup options
    command: [ "--auth" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: raccolta_latte
    ports:
      - 27017:27017
    healthcheck:
      test: mongosh || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

volumes:
  mongodb-data:
