GET https://localhost:8000/auth/admin/admin HTTP/1.1

###

GET https://localhost:8000/api HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiYWRtaW4iOnRydWUsImlhdCI6MTY4NDc0Nzk5NCwiZXhwIjoxNjg0ODM0Mzk0fQ.qq3cXEk_GfSSVEJjRssdG6nGz-5X2OVzGM95Qdb_Lr4


###

###
POST https://localhost:8000/api/user HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiYWRtaW4iOnRydWUsImlhdCI6MTY4NDc2NzMyMCwiZXhwIjoxNjg0ODUzNzIwfQ.vW6FdlwIBvcX_4KYho7cxJHM9UrBENPe3F2y0HMv_04

{
"username": "user",
"password": "password",
"admin": false
}
###

PATCH  https://localhost:8000/api/user/admin HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiYWRtaW4iOnRydWUsImlhdCI6MTY4NDc2NzMyMCwiZXhwIjoxNjg0ODUzNzIwfQ.vW6FdlwIBvcX_4KYho7cxJHM9UrBENPe3F2y0HMv_04

{
"password": "admin",
"admin": true
}

###
GET https://localhost:8000/api/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiYWRtaW4iOnRydWUsImlhdCI6MTY4NDc4NTA3NiwiZXhwIjoxNjg0ODcxNDc2fQ.2yr3URf0TNB9x_x15Cc6ZBV0hA-gadOdTm_Ol5aodxI
