name: Node.js CI

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
    - name: Run tests
      run: yarn test
    # - name: Report test coverage
    #  uses: phoenix-actions/test-reporting@v8
    #  id: test-report
    #  if: always()
    #  with:
    #    name: 'Test Coverage'
    #    path: junit.xml
    #    reporter: jest-junit
